### ISSUE TITLE
Add a constructor option to enable/disable is_cyclec check on adding a new dep

### ISSUE THREAD

**Issue by jorotenev** [yassen-itlabs/depdag#13]
It would be nice to perform an is_cyclic check every time a new dependency is added. Since it involves some processing, we can add a parameter in the constructor of the DAG object to enable/disable this check. By default it should be True - so that we can fail fast in case the dag would become cyclic.

**Comment by yassen-itlabs** [comment]
Thanks, Joro! Good idea to have it optional, as there seem to be use cases where mandatory `is_cyclic()` run on each dag change might be prohibitive.

So yes, graldly accepting this, will work on it soon.
Cheers!
